### PR TITLE
fix(DATAGO-133950): forward unknown attrs through ADK's session-service wrappers

### PR DESCRIPTION
**Pull request by amir-ghasemi**
## Summary

`RetryingSessionService` and `FilteringSessionService` only proxy the explicit `BaseSessionService` API, hiding `DatabaseSessionService` instance attrs that two consumers rely on. Add a narrow `__getattr__` to both wrappers so unknown attribute lookups fall through to the wrapped service.

## Why

Two consumers reach past `BaseSessionService` into the underlying SQL service:

| Consumer | Attribute | Failure mode |
|---|---|---|
| Enterprise `SecretSessionManager.__init__` (`solace_agent_mesh_enterprise/auth/secret_session_manager.py:34`) | `database_session_factory` | **Hard** — `AttributeError` blocks agent startup whenever a SQL `session_service` is configured. This is the staging failure. |
| `common/app_base._get_db_engines_from_components` (line 167) | `db_engine` | **Silent** — `hasattr()` returns `False` through the wrapper, so the agent DB has been quietly dropping out of the broker-level DB health check ever since #1458 landed. |

Staging stack trace from the enterprise pod:

```
File "/opt/venv/lib/python3.11/site-packages/solace_agent_mesh_enterprise/auth/secret_session_manager.py", line 34, in __init__
    self._session_factory = self._session_service.database_session_factory
AttributeError: 'RetryingSessionService' object has no attribute 'database_session_factory'
```

## Fix

Single `__getattr__` on each wrapper that delegates to `self._wrapped`. `__getattr__` only fires on attribute-lookup miss, so the explicit wrapper methods (filtering / retry) still take precedence and add their behaviour; only attributes the wrapper itself doesn't define hit the passthrough. Genuinely missing attributes still raise `AttributeError`.

## Audit of other consumers

I swept the codebase for any other consumer reading non-`BaseSessionService` attributes off the session service. None found beyond the two above:

- `agent/protocol/event_handlers.py:2870`, `agent/adk/runner.py:1602/1618` — standard API calls + truthy checks only.
- `gateway/http_sse/dependencies.py:get_adk_session_service` — uses `create_session_service_from_config` directly without wrapping (#1458's design), so its consumers see the raw `DatabaseSessionService`.
- `gateway/http_sse/routers/sessions.py` and `routers/artifacts.py` — different `session_service` (gateway chat-session metadata module, not ADK).

## Test plan

- [x] New regression tests in `tests/unit/agent/adk/test_auto_summarization_services.py`:
  - `database_session_factory` reachable through `FilteringSessionService`
  - `database_session_factory` reachable through `RetryingSessionService`
  - `database_session_factory` reachable through stacked `Filtering(Retrying(SQL))` (the production composition)
  - `db_engine` reachable via `hasattr()` probe through every wrapper combo (the silent-failure case)
  - Genuinely missing attributes still raise `AttributeError`
- [x] All 17 tests in the file pass locally.
- [x] Live-reproduced the exact `service.database_session_factory` lookup that enterprise's `SecretSessionManager` performs — works through the production wrapper stack.
- [ ] Verify on staging after merge that the enterprise pod starts and that the agent DB now appears in the broker DB health check.

### CODE REVIEW

**Review by efunneko — APPROVED** [review]
LG
